### ISSUE TITLE
DOC: Restructuring as Jupyter book

### ISSUE THREAD

**Issue by josephmje** [VectorInstitute/forecasting-bootcamp#21]
I was wondering whether restructuring this repository into a Jupyter book would be a welcome addition? See the [scikit-learn course](https://inria.github.io/scikit-learn-mooc/index.html) for an example.

I think having a table of contents/sidebar to navigate would help with the flow of the different notebooks. 

You would also be add a button to launch any of the notebooks on Google Colab for some interactivity.

I'm happy to work on this update if it would be useful.

**Comment by jewelltaylor** [comment]
I think that is a very interesting idea - something that could be useful for this and other projects involving knowledge transfer. Let me bring it up to the team at the meeting this week and I will get back to you! Thanks, a lot!

**Comment by josephmje** [comment]
@jewelltaylor I'm just following up on this idea. I created a quick mockup of what this could look like [here](https://josephmje.github.io/forecasting-bootcamp). At the moment, it's set up to assume that the Jupyter notebooks have already been fully executed. It can be setup to execute in real time and deploy but for that case, I'm not sure how long each notebook would take to run.
